
MOD_NAME := tfs_kmod

obj-m += $(MOD_NAME).o

$(MOD_NAME)-y := tfs.o  tfs_module.o

cxx-prefix := " $(HOSTCXX) [M]  "

cxx-selected-flags = $(shell echo $(KBUILD_CFLAGS) \
            | sed s/-D\"KBUILD.\"//g \
            | sed s/-Werror=strict-prototypes//g \
            | sed s/-Werror=implicit-function-declaration//g \
            | sed s/-Werror=implicit-int//g \
            | sed s/-Wdeclaration-after-statement//g \
            | sed s/-Wno-pointer-sign//g \
            | sed s/-std=gnu89//g \
            | sed s/-Werror=incompatible-pointer-types//g \
            | sed s/-Werror=designated-init//g \
            | sed s/-std=gnu90//g )


cxxflags = $(FLAGS) \
            $(cxx-selected-flags) \
            -fno-builtin \
            -nostdlib \
            -fno-rtti \
            -fno-exceptions \
            -std=c++0x -DKERNEL_MODE

%.o: %.cc
	$(HOSTCXX) $(cxxflags) -c -I/home/rove/Projects/tfs/kmod/../lib/include $< -o $@
	@echo -n > $$(dirname $@)/.$$(basename $@).cmd



